# Generated by Django 4.2.3 on 2023-07-21 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_remove_dish_cooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
