# Generated by Django 4.2.3 on 2023-07-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_category_options_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
