# Generated by Django 4.2.3 on 2023-07-21 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category__name'], 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(null=True, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
