# Generated by Django 4.2.3 on 2023-07-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_alter_dish_cooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cooks',
        ),
    ]
